version: '3.5'

services:
  api: 
    build: ./api
    expose: 
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./api:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend'
      - 'frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - "api:api"
  # api:
  #   build: ./api
  #   command: python api.py run -h 0.0.0.0
  #   volumes:
  #     - ./api/:/usr/src/app/
  #   ports:
  #     - 5000:5000
  #   env_file:
  #     - ./api/.flaskenv